# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

name: DNSDKLoginKit

include:
  - ../xcodegen_project_common.yml

projectReferences:
  FBSDKCoreKit_Basics:
    path: ../FBSDKCoreKit_Basics/FBSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../FBSDKCoreKit/FBSDKCoreKit.xcodeproj
  TestTools:
    path: ../TestTools/TestTools.xcodeproj

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

settings:
  base:
    # Some iOS defaults will be overridden by Xcodegen.
    # We need to explicitly set them to maintain parity with
    # the project file being replaced
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
    ENABLE_NS_ASSERTIONS: YES

targets:
  FBSDKLoginKit-Static:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKLoginKit
    sources:
      - path: DNSDKLoginKit
        headerVisibility: public
        excludes:
          - Internal
          - Info.plist
          - Swift
      - path: DNSDKLoginKit/Internal
        headerVisibility: project
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/DNSDKLoginKit-Static.xcconfig
      Release: Configurations/DNSDKLoginKit-Static.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Static
        link: false
      - target: FBSDKCoreKit/FBSDKCoreKit-Static
        link: false
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
  FBSDKLoginKit-Dynamic:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKLoginKit
    sources:
      - path: DNSDKLoginKit
        headerVisibility: public
        excludes:
          - Internal
          - Info.plist
          - Swift
      - path: DNSDKLoginKit/Internal
        headerVisibility: project
        createIntermediateGroups: true
    configFiles:
      Debug: Configurations/DNSDKLoginKit-Dynamic.xcconfig
      Release: Configurations/DNSDKLoginKit-Dynamic.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Dynamic
      - target: FBSDKCoreKit/FBSDKCoreKit-Dynamic
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
  FBSDKLoginKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DNSDKLoginKitTests
    configFiles:
      Debug: Configurations/DNSDKLoginKitTests.xcconfig
      Release: Configurations/DNSDKLoginKitTests.xcconfig
    dependencies:
      - target: DNSDKLoginKit-Dynamic
        embed: false
      - target: TestTools/TestTools
        embed: false
    settings:
      GCC_WARN_UNUSED_FUNCTION: NO

schemes:
  FBSDKLoginKit-Static:
    build:
      targets:
        FBSDKLoginKit-Static: all
  FBSDKLoginKit-Dynamic:
    build:
      targets:
        FBSDKLoginKit-Dynamic: all
    test:
      targets:
        - DNSDKLoginKitTests
      gatherCoverageData: true
      coverageTargets:
        - DNSDKLoginKit-Dynamic
