# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

name: DNSDKGamingServicesKit

include:
  - ../xcodegen_project_common.yml

projectReferences:
  FBSDKCoreKit_Basics:
    path: ../DNSDKCoreKit_Basics/DNSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../FBSDKCoreKit/FBSDKCoreKit.xcodeproj
  FBSDKShareKit:
    path: ../DNSDKShareKit/DNSDKShareKit.xcodeproj
  TestTools:
    path: ../TestTools/TestTools.xcodeproj

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

settings:
  base:
    # Some iOS defaults will be overridden by Xcodegen.
    # We need to explicitly set them to maintain parity with
    # the project file being replaced
    ENABLE_NS_ASSERTIONS: YES

schemes:
  FBSDKGamingServicesKit-Static:
    build:
      targets:
        FBSDKGamingServicesKit-Static: all
  FBSDKGamingServicesKit-Dynamic:
    build:
      targets:
        FBSDKGamingServicesKit-Dynamic: all
    test:
      targets:
        - DNSDKGamingServicesKitTests
      gatherCoverageData: true
      coverageTargets:
        - DNSDKGamingServicesKit-Dynamic

targets:
  FBSDKGamingServicesKit-Dynamic:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKGamingServicesKit
    sources:
      - path: DNSDKGamingServicesKit
    configFiles:
      Debug: Configurations/DNSDKGamingServicesKit-Dynamic.xcconfig
      Release: Configurations/DNSDKGamingServicesKit-Dynamic.xcconfig
    dependencies:
      - target: DNSDKCoreKit_Basics/DNSDKCoreKit_Basics-Dynamic
      - target: FBSDKCoreKit/FBSDKCoreKit-Dynamic
      - target: DNSDKShareKit/DNSDKShareKit-Dynamic
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
    transitivelyLinkDependencies: true
  FBSDKGamingServicesKit-Static:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKGamingServicesKit
    sources:
      - path: DNSDKGamingServicesKit
    configFiles:
      Debug: Configurations/DNSDKGamingServicesKit-Static.xcconfig
      Release: Configurations/DNSDKGamingServicesKit-Static.xcconfig
    dependencies:
      - target: DNSDKCoreKit_Basics/DNSDKCoreKit_Basics-Static
        link: false
      - target: FBSDKCoreKit/FBSDKCoreKit-Static
        link: false
      - target: DNSDKShareKit/DNSDKShareKit-Static
        link: false
    settings:
      CLANG_WARN_STRICT_PROTOTYPES: NO
  FBSDKGamingServicesKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DNSDKGamingServicesKitTests
    configFiles:
      Debug: Configurations/DNSDKGamingServicesKitTests.xcconfig
      Release: Configurations/DNSDKGamingServicesKitTests.xcconfig
    dependencies:
      - target: TestTools/TestTools
        embed: false
      - target: DNSDKGamingServicesKit-Dynamic
        embed: false
    settings:
      GCC_WARN_UNUSED_FUNCTION: NO
    transitivelyLinkDependencies: true
