# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

name: DNSDKCoreKit_Basics

include:
  - ../xcodegen_project_common.yml

projectReferences:
  TestTools:
    path: ../TestTools/TestTools.xcodeproj

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

targets:
  FBSDKCoreKit_Basics-Static:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKCoreKit_Basics
    sources:
      - path: DNSDKCoreKit_Basics/include
        headerVisibility: public
      - path: DNSDKCoreKit_Basics
        headerVisibility: project
        excludes:
          - include
    configFiles:
      Debug: Configurations/DNSDKCoreKit_Basics-Static.xcconfig
      Release: Configurations/DNSDKCoreKit_Basics-Static.xcconfig
    settings:
      GCC_PREFIX_HEADER: DNSDKCoreKit_Basics/FBSDKCoreKitBasics-Prefix-Header.h
  FBSDKCoreKit_Basics-Dynamic:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    dependencies:
      - sdk: UIKit.framework
      - sdk: libz.tbd
    platform: iOS
    productName: DNSDKCoreKit_Basics
    sources:
      - path: DNSDKCoreKit_Basics/include
        headerVisibility: public
      - path: DNSDKCoreKit_Basics
        headerVisibility: project
        excludes:
          - include
    configFiles:
      Debug: Configurations/DNSDKCoreKit_Basics-Dynamic.xcconfig
      Release: Configurations/DNSDKCoreKit_Basics-Dynamic.xcconfig
    settings:
      GCC_PREFIX_HEADER: DNSDKCoreKit_Basics/FBSDKCoreKitBasics-Prefix-Header.h
  FBSDKCoreKit_BasicsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DNSDKCoreKit_BasicsTests
    configFiles:
      Debug: Configurations/DNSDKCoreKit_BasicsTests.xcconfig
      Release: Configurations/DNSDKCoreKit_BasicsTests.xcconfig
    dependencies:
      - target: DNSDKCoreKit_Basics-Dynamic
      - target: TestTools/TestTools
        link: false
        embed: false

schemes:
  FBSDKCoreKit_Basics-Static:
    build:
      targets:
        FBSDKCoreKit_Basics-Static: all
  FBSDKCoreKit_Basics-Dynamic:
    build:
      targets:
        FBSDKCoreKit_Basics-Dynamic: all
    test:
      targets: [DNSDKCoreKit_BasicsTests]
      gatherCoverageData: true
      coverageTargets:
        - DNSDKCoreKit_Basics-Dynamic
