# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

name: DNSDKShareKit

include:
  - ../xcodegen_project_common.yml

projectReferences:
  FBSDKCoreKit_Basics:
    path: ../FBSDKCoreKit_Basics/FBSDKCoreKit_Basics.xcodeproj
  FBSDKCoreKit:
    path: ../FBSDKCoreKit/FBSDKCoreKit.xcodeproj
  TestTools:
    path: ../TestTools/TestTools.xcodeproj

configFiles:
  Debug: Configurations/Shared/Configuration/Debug.xcconfig
  Release: Configurations/Shared/Configuration/Release.xcconfig

settings:
  base:
    # Some iOS defaults will be overridden by Xcodegen.
    # We need to explicitly set them to maintain parity with
    # the project file being replaced
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
    ENABLE_NS_ASSERTIONS: YES

targets:
  FBSDKShareKit-Static:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKShareKit
    sources:
      - path: DNSDKShareKit
        headerVisibility: public
    configFiles:
      Debug: Configurations/DNSDKShareKit-Static.xcconfig
      Release: Configurations/DNSDKShareKit-Static.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Static
        link: false
      - target: FBSDKCoreKit/FBSDKCoreKit-Static
        link: false
    settings:
      CLANG_ENABLE_MODULES: YES
      DEFINES_MODULE: YES
  FBSDKShareKit-Dynamic:
    templates:
      - SwiftlintBuildPhaseTemplate
    type: framework
    platform: iOS
    productName: DNSDKShareKit
    sources:
      - path: DNSDKShareKit
        headerVisibility: public
    configFiles:
      Debug: Configurations/DNSDKShareKit-Dynamic.xcconfig
      Release: Configurations/DNSDKShareKit-Dynamic.xcconfig
    dependencies:
      - target: FBSDKCoreKit_Basics/FBSDKCoreKit_Basics-Dynamic
      - target: FBSDKCoreKit/FBSDKCoreKit-Dynamic
      - sdk: UIKit.framework
      - sdk: CoreGraphics.framework
      - sdk: Photos.framework
      - sdk: Social.framework
        weak: true
    settings:
      CLANG_ENABLE_MODULES: YES
      DEFINES_MODULE: YES
  FBSDKShareKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DNSDKShareKitTests
    configFiles:
      Debug: Configurations/DNSDKShareKitTests.xcconfig
      Release: Configurations/DNSDKShareKitTests.xcconfig
    dependencies:
      - target: DNSDKShareKit-Dynamic
        embed: false
      - target: TestTools/TestTools
        embed: false
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
      GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS: NO
schemes:
  FBSDKShareKit-Static:
    build:
      targets:
        FBSDKShareKit-Static: all
  FBSDKShareKit-Dynamic:
    build:
      targets:
        FBSDKShareKit-Dynamic: all
    test:
      targets:
        - DNSDKShareKitTests
      gatherCoverageData: true
      coverageTargets:
        - DNSDKShareKit-Dynamic
