appId: xyz.blueskyweb.app
---
- runScript:
    file: ../setupServer.js
    env:
        SERVER_PATH: ?users
- runFlow:
    file: ../setupApp.yml
- tapOn:
    id: "e2eSignInAlice"

# Post an image with the porn label
- tapOn:
    id: "composeFAB"
- inputText: "Post with an image"
- tapOn:
    id: "openGalleryBtn"
- tapOn:
    id: "labelsBtn"
- tapOn:
    label: "Tap on porn"
    point: 78%,67%
- tapOn:
    label: "Tap on confirm"
    point: 51%,92%
- tapOn:
    id: "composerPublishBtn"
- tapOn:
    id: "e2eRefreshHome"
- assertVisible: "Adult Content"